blacklist:
- moveit_commander
- moveit_setup_assistant
- moveit_ros_robot_interaction
- moveit_ros_visualization
- moveit_ros_benchmarks
- moveit_controller_manager_example
- moveit_ros_warehouse
- moveit_ros_manipulation
- moveit_visual_tools
- rviz_visual_tools
- moveit_chomp_optimizer_adapter
- moveit_planners_chomp
- chomp_motion_planner
build_space: build
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: devel
extend_path: /opt/ros/kinetic
install: false
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
